"""
Stage 06_4:
- Read stage outputs generated by 06_3.
- Export regrouped lake shp/csv from red-point WSE ranges.
- Render ranked branch plots after shp export.
"""

import os
import re
import sys
import importlib.util
from pathlib import Path
from collections import defaultdict

import pandas as pd


SCRIPT_DIR = Path(__file__).resolve().parent
STAGE06_3_PATH = SCRIPT_DIR / "06_3_plot_branchwise_red_chain_with_merge_anchor.py"
STAGE_CSV_PATTERN = re.compile(r"^lake_(\d+)_branch_(\d+)_stage_v([CD])\.csv$", re.IGNORECASE)
PROJECT_ROOT_DIR = SCRIPT_DIR.parent
DEFAULT_RESULT_ROOT_DIR = PROJECT_ROOT_DIR / "result1"
RESULT_ROOT_DIR = Path(str(os.environ.get("OUTPUT_ROOT_DIR", "")).strip() or DEFAULT_RESULT_ROOT_DIR)
OUTPUT_ROOT_DIR = RESULT_ROOT_DIR / "06_4_export_shp_and_ranked_from_06_3"
OUTPUT_MAP_MAIN_DIR = OUTPUT_ROOT_DIR / "map_main"


def load_stage06_3_module():
    module_name = "stage06_3_module_for_06_4"
    existing = sys.modules.get(module_name)
    if existing is not None:
        return existing

    spec = importlib.util.spec_from_file_location(module_name, str(STAGE06_3_PATH))
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Failed to load stage 06_3 module: {STAGE06_3_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def _to_bool(value):
    if isinstance(value, bool):
        return value
    if pd.isna(value):
        return False
    text = str(value).strip().lower()
    return text in {"1", "true", "t", "yes", "y"}


def load_stage_records_from_csv(csv_path):
    if not os.path.exists(csv_path):
        return []
    df = pd.read_csv(csv_path, encoding="utf-8-sig")
    if df.empty:
        return []

    df = df.copy()
    df["date_dt"] = pd.to_datetime(df.get("date"), errors="coerce")
    df["wse_m"] = pd.to_numeric(df.get("wse_m"), errors="coerce")
    df["wse_std"] = pd.to_numeric(df.get("wse_std"), errors="coerce")
    if "point_color" not in df.columns:
        df["point_color"] = ""
    if "is_noise" not in df.columns:
        df["is_noise"] = False
    if "noise_reason" not in df.columns:
        df["noise_reason"] = ""

    df = df.dropna(subset=["date_dt", "wse_m"]).copy()
    if df.empty:
        return []

    df["branch_index"] = pd.to_numeric(df.get("branch_index"), errors="coerce").astype("Int64")
    df = df.sort_values(["date_dt", "branch_index", "wse_m"]).reset_index(drop=True)

    records = []
    for row in df.to_dict("records"):
        records.append(
            {
                "date": pd.Timestamp(row["date_dt"]),
                "wse": float(row["wse_m"]),
                "wse_std": pd.NA if pd.isna(row.get("wse_std")) else float(row["wse_std"]),
                "point_color": str(row.get("point_color", "")),
                "is_noise": _to_bool(row.get("is_noise", False)),
                "noise_reason": str(row.get("noise_reason", "")),
            }
        )
    return records


def collect_jobs_for_method(stage06_3, base_module, method_paths, selected_versions):
    area_points_df = stage06_3.load_branch_area_points(method_paths["curve_point_csv"])
    version_jobs_map = defaultdict(list)
    version_range_rows_map = defaultdict(list)

    csv_root = Path(method_paths["csv_dir"])
    for pixc_version in selected_versions:
        version = str(pixc_version).upper()
        version_csv_dir = csv_root / f"v{version}"
        if not version_csv_dir.exists():
            continue

        for csv_path in sorted(version_csv_dir.glob("lake_*_branch_*_stage_v*.csv")):
            m = STAGE_CSV_PATTERN.match(csv_path.name)
            if m is None:
                continue
            lake_id = int(m.group(1))
            branch_index = int(m.group(2))
            file_version = str(m.group(3)).upper()
            if file_version != version:
                continue

            stage_records = load_stage_records_from_csv(str(csv_path))
            if not stage_records:
                continue
            stage06_3.add_same_day_plot_offsets(stage_records)
            stage_segments = base_module.rebuild_segments(stage_records, base_module.PARAMS, force_red=False)

            red_point_count = stage06_3.count_red_points(stage_records, base_module)
            branch_area_df = stage06_3.get_branch_area_series(area_points_df, lake_id, branch_index)
            fixed_xlim = (stage06_3.PLOT_X_GLOBAL_START, stage06_3.PLOT_X_GLOBAL_END)

            if red_point_count >= int(stage06_3.RED_POINTS_MIN_TO_SAVE):
                red_only_df = stage06_3.prepare_red_only_output_df(
                    stage_records,
                    branch_index=branch_index,
                    lake_id=lake_id,
                    pixc_version=version,
                    base_module=base_module,
                )
                range_info = stage06_3.summarize_red_wse_range(red_only_df, lake_id, branch_index, version)
                if range_info is not None:
                    version_range_rows_map[version].append(range_info)
                kind = "full"
            else:
                kind = "red_days_lt5"

            version_jobs_map[version].append(
                {
                    "kind": kind,
                    "lake_id": lake_id,
                    "branch_index": branch_index,
                    "pixc_version": version,
                    "stage_records": stage_records,
                    "stage_segments": stage_segments,
                    "fixed_xlim": fixed_xlim,
                    "branch_area_df": branch_area_df.copy() if branch_area_df is not None else pd.DataFrame(),
                }
            )

    return version_jobs_map, version_range_rows_map


def main():
    stage06_3 = load_stage06_3_module()
    base = stage06_3.load_base_module()
    filtered_lake_gdf = stage06_3.load_filtered_lake_polygons()
    os.makedirs(OUTPUT_ROOT_DIR, exist_ok=True)
    os.makedirs(OUTPUT_MAP_MAIN_DIR, exist_ok=True)
    # Route shp/csv exports from 06_3 helper into the dedicated 06_4 output root.
    stage06_3.MAP_MAIN_DIR = OUTPUT_MAP_MAIN_DIR

    selected_versions = [str(v).upper() for v in stage06_3.PIXC_VERSIONS if str(v).upper() in {"C", "D"}]
    total_plots_all_methods = 0

    for method_name in base.METHOD_NAMES:
        input_method_paths = stage06_3.make_method_paths(base, method_name)
        ranked_plot_root_dir = os.path.join(str(OUTPUT_ROOT_DIR), method_name, "ranked")
        os.makedirs(ranked_plot_root_dir, exist_ok=True)

        version_jobs_map, version_range_rows_map = collect_jobs_for_method(
            stage06_3=stage06_3,
            base_module=base,
            method_paths=input_method_paths,
            selected_versions=selected_versions,
        )

        rank_map_by_version = {}
        for pixc_version, range_rows in version_range_rows_map.items():
            ranked_gdf = stage06_3.export_lakes_with_wse_range(
                method_name,
                range_rows,
                shp_gdf=filtered_lake_gdf,
                display_lake_id_map={1: 1},
                out_tag=f"v{str(pixc_version).lower()}",
            )

            rank_map = {}
            if ranked_gdf is not None and not ranked_gdf.empty:
                old_col = "old_lake_id" if "old_lake_id" in ranked_gdf.columns else "lake_id"
                if "lake_id_new" in ranked_gdf.columns:
                    rank_map = {
                        int(old_id): int(new_id)
                        for old_id, new_id in zip(ranked_gdf[old_col], ranked_gdf["lake_id_new"])
                        if pd.notna(old_id) and pd.notna(new_id)
                    }
            rank_map_by_version[str(pixc_version).upper()] = rank_map

        total_plots = 0
        for pixc_version, jobs in version_jobs_map.items():
            ranked_version_root_dir = os.path.join(ranked_plot_root_dir, f"v{str(pixc_version).lower()}")
            ranked_with_noise_dir = os.path.join(ranked_version_root_dir, "with_noise")
            ranked_no_noise_dir = os.path.join(ranked_version_root_dir, "no_noise")
            ranked_no_noise_dual_axis_dir = os.path.join(ranked_version_root_dir, stage06_3.DUAL_AREA_FOLDER_NAME)
            ranked_red_days_lt5_dir = os.path.join(ranked_version_root_dir, stage06_3.RED_DAYS_LT5_FOLDER_NAME)
            ranked_stage_csv_dir = os.path.join(ranked_version_root_dir, "ranked_stage_csv")
            ranked_red_csv_dir = os.path.join(ranked_version_root_dir, "ranked_red_wse_csv")
            ranked_lake_csv_dir = os.path.join(ranked_version_root_dir, "ranked_lake_csv")
            for d in [
                ranked_with_noise_dir,
                ranked_no_noise_dir,
                ranked_no_noise_dual_axis_dir,
                ranked_red_days_lt5_dir,
                ranked_stage_csv_dir,
                ranked_red_csv_dir,
                ranked_lake_csv_dir,
            ]:
                os.makedirs(d, exist_ok=True)

            rank_map = rank_map_by_version.get(str(pixc_version).upper(), {})
            lake_stage_tables = defaultdict(list)
            lake_red_tables = defaultdict(list)
            for job in jobs:
                display_lake_id = rank_map.get(int(job["lake_id"]))
                if display_lake_id is None:
                    continue

                stage_df = stage06_3.prepare_branch_output_df(job["stage_records"], job["branch_index"])
                stage_df.insert(0, "pixc_version", str(job["pixc_version"]).upper())
                stage_df.insert(0, "orig_lake_id", int(job["lake_id"]))
                stage_df.insert(0, "lake_id_new", int(display_lake_id))
                stage_csv = os.path.join(
                    ranked_stage_csv_dir,
                    stage06_3.build_ranked_plot_filename(
                        job["lake_id"],
                        job["branch_index"],
                        pixc_version=job["pixc_version"],
                        suffix=".csv",
                        display_lake_id=display_lake_id,
                        extra_tag="stage",
                    ),
                )
                stage_df.to_csv(stage_csv, index=False, encoding="utf-8-sig")
                lake_stage_tables[(int(display_lake_id), int(job["lake_id"]))].append(stage_df.copy())

                if job["kind"] == "red_days_lt5":
                    ranked_png = os.path.join(
                        ranked_red_days_lt5_dir,
                        stage06_3.build_ranked_plot_filename(
                            job["lake_id"],
                            job["branch_index"],
                            pixc_version=job["pixc_version"],
                            display_lake_id=display_lake_id,
                        ),
                    )
                    stage06_3.render_branch_plot(
                        base,
                        job["lake_id"],
                        job["branch_index"],
                        job["stage_records"],
                        job["stage_segments"],
                        ranked_png,
                        show_noise=True,
                        fixed_xlim=job["fixed_xlim"],
                        display_lake_id=display_lake_id,
                    )
                    total_plots += 1
                    continue

                red_only_df = stage06_3.prepare_red_only_output_df(
                    job["stage_records"],
                    branch_index=job["branch_index"],
                    lake_id=job["lake_id"],
                    pixc_version=job["pixc_version"],
                    base_module=base,
                )
                if not red_only_df.empty:
                    red_only_df.insert(0, "orig_lake_id", int(job["lake_id"]))
                    red_only_df.insert(0, "lake_id_new", int(display_lake_id))
                    red_csv = os.path.join(
                        ranked_red_csv_dir,
                        stage06_3.build_ranked_plot_filename(
                            job["lake_id"],
                            job["branch_index"],
                            pixc_version=job["pixc_version"],
                            suffix=".csv",
                            display_lake_id=display_lake_id,
                            extra_tag="red_wse",
                        ),
                    )
                    red_only_df.to_csv(red_csv, index=False, encoding="utf-8-sig")
                    lake_red_tables[(int(display_lake_id), int(job["lake_id"]))].append(red_only_df.copy())

                ranked_no_noise_png = os.path.join(
                    ranked_no_noise_dir,
                    stage06_3.build_ranked_plot_filename(
                        job["lake_id"],
                        job["branch_index"],
                        pixc_version=job["pixc_version"],
                        display_lake_id=display_lake_id,
                    ),
                )
                ranked_with_noise_png = os.path.join(
                    ranked_with_noise_dir,
                    stage06_3.build_ranked_plot_filename(
                        job["lake_id"],
                        job["branch_index"],
                        pixc_version=job["pixc_version"],
                        display_lake_id=display_lake_id,
                    ),
                )
                ranked_dual_axis_png = os.path.join(
                    ranked_no_noise_dual_axis_dir,
                    stage06_3.build_ranked_plot_filename(
                        job["lake_id"],
                        job["branch_index"],
                        pixc_version=job["pixc_version"],
                        display_lake_id=display_lake_id,
                    ),
                )
                stage06_3.render_branch_plot(
                    base,
                    job["lake_id"],
                    job["branch_index"],
                    job["stage_records"],
                    job["stage_segments"],
                    ranked_no_noise_png,
                    show_noise=False,
                    fixed_xlim=job["fixed_xlim"],
                    display_lake_id=display_lake_id,
                )
                stage06_3.render_branch_dual_axis_plot(
                    base,
                    job["lake_id"],
                    job["branch_index"],
                    job["stage_records"],
                    ranked_dual_axis_png,
                    job["branch_area_df"],
                    fixed_xlim=job["fixed_xlim"],
                    display_lake_id=display_lake_id,
                )
                stage06_3.render_branch_plot(
                    base,
                    job["lake_id"],
                    job["branch_index"],
                    job["stage_records"],
                    job["stage_segments"],
                    ranked_with_noise_png,
                    show_noise=True,
                    fixed_xlim=job["fixed_xlim"],
                    display_lake_id=display_lake_id,
                )
                total_plots += 3

            for (display_lake_id, orig_lake_id), table_list in lake_stage_tables.items():
                if table_list:
                    out_df = pd.concat(table_list, ignore_index=True)
                    out_df = out_df.sort_values(["branch_index", "date", "wse_m"]).reset_index(drop=True)
                    out_csv = os.path.join(
                        ranked_lake_csv_dir,
                        f"Lake_{display_lake_id}_orig_{orig_lake_id}_all_branches_stage_v{str(pixc_version).upper()}.csv",
                    )
                    out_df.to_csv(out_csv, index=False, encoding="utf-8-sig")
            for (display_lake_id, orig_lake_id), table_list in lake_red_tables.items():
                if table_list:
                    out_df = pd.concat(table_list, ignore_index=True)
                    out_df = out_df.sort_values(["branch_index", "date", "wse_m"]).reset_index(drop=True)
                    out_csv = os.path.join(
                        ranked_lake_csv_dir,
                        f"Lake_{display_lake_id}_orig_{orig_lake_id}_all_branches_red_wse_v{str(pixc_version).upper()}.csv",
                    )
                    out_df.to_csv(out_csv, index=False, encoding="utf-8-sig")

        total_plots_all_methods += total_plots
        print(f"[06_4] done {method_name}, ranked_plots={total_plots}", flush=True)

    print(f"[06_4] all done, ranked_plots={total_plots_all_methods}", flush=True)


if __name__ == "__main__":
    main()
